config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :alternatives
  resources :criterions do
    resources :alternative_criterion_comparisons
  end
  resources :criterion_comparisons
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alternative_criterion_comparison.rb
class AlternativeCriterionComparison < ApplicationRecord
  belongs_to :criterion
  belongs_to :alternative, class_name: 'Alternative'
  belongs_to :other_alternative, class_name: 'Alternative' 
end

app/controllers/alternative_criterion_comparisons_controller.rb
class AlternativeCriterionComparisonsController < ApplicationController
  before_action :authenticate_user! , except: [:index]
  before_action :set_acc, only: [:edit, :update, :destroy]
  before_action :set_alt
  def index
    begin
        @data = get_comparison_table
        @c = 0
        @sumFix = []
        @data.each_with_index do |fd1, index1|
          @sumOne = 0
          @data.each_with_index do |fd, index|
            @sumOne += @data[index][index1]
          end
          @sumFix[@c] = @sumOne
          @c += 1
        end

        @s = 0
        @normalFix = []
        @average = []
        @data.each_with_index do |fd1, index1|
          @sumAv = 0
          @norm = []
          @l = 0
          @data.each_with_index do |fd, index|
            @norm[@l] = @data[index1][index] / @sumFix[index]
            @sumAv += @norm[@l]
            @l += 1
          end
          @average[@s] = @sumAv/@data.count
          @normalFix[@s] = @norm
          @s += 1
        end

        @x = 0
        @sumNormalFix = []
        @normalFix.each_with_index do |fd1, index1|
          @sumOne = 0
          @normalFix.each_with_index do |fd, index|
            @sumOne += @normalFix[index][index1]
          end
          @sumNormalFix[@x] = @sumOne
          @x += 1
        end
        @sumNormalFix[@x] = @average.inject(0, :+)

    rescue
        redirect_to new_criterion_alternative_criterion_comparison_path(@criterion)
        flash[:warning] = 'Lengkapi Perbandingan terlebih dahulu'
    end
  end

  def self.get_average
    @krite = Criterion.all.order(id: :asc)
    @n = 0
    @averageFix = []
    @krite.each_with_index do |altrr, indexho|
      @averageTemp = []
      @data = self.get_comparison_table(altrr.id)
      @c = 0
      @sumFix = []
      @data.each_with_index do |fd1, index1|
        @sumOne = 0
        @data.each_with_index do |fd, index|
          @sumOne += @data[index][index1]
        end
        @sumFix[@c] = @sumOne
        @c += 1
      end

      @s = 0
      @normalFix = []
      @average = []
      @data.each_with_index do |fd1, index1|
        @sumAv = 0
        @norm = []
        @l = 0
        @data.each_with_index do |fd, index|
          @norm[@l] = @data[index1][index] / @sumFix[index]
          @sumAv += @norm[@l]
          @l += 1
        end
        @average[@s] = @sumAv/@data.count
        @normalFix[@s] = @norm
        @averageTemp = @average
        @s += 1
      end
      @averageFix[indexho] = @averageTemp
    end

    return @averageFix
  end

  def new
    if Alternative.count > 1
      @acc = AlternativeCriterionComparison.new(criterion_id: params[:criterion_id])
      @curretAlt = get_comparison_criterion
    else
      @acc = nil
    end
  end

  def create
    @acc = AlternativeCriterionComparison.new(acc_params)
    if @acc.save
      redirect_to  new_criterion_alternative_criterion_comparison_path(@criterion), notice: 'Berhasil menambahkan perbandingan'
    else
      redirect_to new_criterion_alternative_criterion_comparison_path(@criterion)
      flash[:warning] = 'Gagal menambahkan, periksa kembali'
    end
  end

  def edit
    @curretAlt = [@acc.alternative_id, @acc.other_alternative_id]
  end

  def update
    if @acc.update(cc_params)
      redirect_to new_criterion_alternative_criterion_comparison_path(@criterion), notice: 'Berhasil update perbandingan'
    else
      redirect_to new_criterion_alternative_criterion_comparison_path(@criterion)
      flash[:warning] = 'Gagal update, periksa kembali'
    end
  end

  def destroy
    @acc.destroy
    redirect_to new_criterion_alternative_criterion_comparison_path(@criterion), notice: 'Perbandingan berhasil dihapus'
  end

  private

  def set_acc
    @acc = AlternativeCriterionComparison.find(params[:id])
  end

  def set_alt
    @criterion = Criterion.find(params[:criterion_id])
  end


  def acc_params
    params.require(:alternative_criterion_comparison).permit(:criterion_id, :alternative_id, :comparison, :other_alternative_id)
  end

  def get_comparison_criterion
    @alt = Alternative.all.order(id: :asc) unless Alternative.nil?
    @ccs = AlternativeCriterionComparison.where(criterion_id: @criterion.id).order(alternative_id: :asc, other_alternative_id: :asc)
    @sumAlt = @alt.count
    @curretAlt1 = nil
    @curretAlt2 = nil

    if @ccs.empty?
      @curretAlt1 = @alt.first.id
      @curretAlt2 = @alt.first.next.id
    else
      @ketemu = false
      @alt.each do |c|
        if @ccs.where(alternative_id: c.id).exists?
          @alt1 = @ccs.where(alternative_id: c.id)
          @alt2 = @ccs.where(other_alternative_id: c.id)

          @alternatif = c.next
          @alt1.each do |cr|
            @stop = false
            @alt1.each do |cr2|
              if cr2.other_alternative_id == @alternatif.id
                @stop = true
              end
              break if @stop == true
            end
            break if @stop == false
            @alternatif = @alternatif.next
          end


          if (@alt1.count + @alt2.count) < @sumAlt-1
            @curretAlt1 = c.id
            @curretAlt2 = @alternatif.id
            @ketemu = true
          end

        else
          begin
            @curretAlt1 = c.id
            @curretAlt2 = c.next.id
            @ketemu = true
          rescue
            @ketemu = true
          end
        end
        break if @ketemu == true
      end
    end
    return [@curretAlt1, @curretAlt2]
  end

  def get_comparison_table
    @alternatif = Alternative.all.order(id: :asc)
    @sum = @alternatif.count
    @data = []
    @n = 0
    @alternatif.each do |k|
      @dt = AlternativeCriterionComparison.where(criterion_id: @criterion.id, alternative_id: k.id).order(other_alternative_id: :asc)
      @i = 0
      @dat = []
      @dt.each do |dt|
        @dat[@i] = dt.comparison
        @i += 1
      end
      @data[@n] = @dat
      @n += 1
    end
    @fixdata = Array.new(@sum) { Array.new(@sum) }

    @alternatif.each_with_index do |k, i|
      (0..i).each do |n|
        if i == n
          @fixdata[i][n] = 1.to_f
          @k = n+1
          @data[i].each do |d|
            @fixdata[i][@k] = d
            @k += 1
          end
        elsif n < i
          @fixdata[i][n] = 1/@fixdata[n][i]
        end
      end
    end
    return @fixdata
  end

  def self.get_comparison_table(*id)
    @alternatif = Alternative.all.order(id: :asc)
    @sum = @alternatif.count
    @data = []
    @n = 0
    @alternatif.each do |k|
      @dt = AlternativeCriterionComparison.where(criterion_id: id, alternative_id: k.id).order(other_alternative_id: :asc)
      @i = 0
      @dat = []
      @dt.each do |dt|
        @dat[@i] = dt.comparison
        @i += 1
      end
      @data[@n] = @dat
      @n += 1
    end
    @fixdata = Array.new(@sum) { Array.new(@sum) }

    @alternatif.each_with_index do |k, i|
      (0..i).each do |n|
        if i == n
          @fixdata[i][n] = 1.to_f
          @k = n+1
          @data[i].each do |d|
            @fixdata[i][@k] = d
            @k += 1
          end
        elsif n < i
          @fixdata[i][n] = 1/@fixdata[n][i]
        end
      end
    end
    return @fixdata
  end
end

app/helpers/alternative_criterion_comparisons_helper.rb
module AlternativeCriterionComparisonsHelper
end

app/views/alternative_criterion_comparisons/_form.html.erb
<hr>
<%= form_for [@criterion, @acc], :html => {:class => "form-horizontal form-label-left"} do |f| %>
  <%= render "shared/errors", object: @acc %>
  <div class="form-group">
    <%= f.label '', "Nama Alternatif 1 :", class: "control-label col-md-3 col-sm-3 col-xs-12" %>
      <div class="col-md-6 col-sm-6 col-xs-12">
          <%= collection_select('', '', Alternative.where(id: @nowAlt[0]), :id, :name, {}, {:class => "form-control", disabled: true}) %>
      </div>
  </div>
  <div class="ln_solid"></div>
  <div class="form-group">
    <%= f.label '', "Perbandingan :", class: "control-label col-md-3 col-sm-3 col-xs-12" %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.number_field :comparison, { autofocus: :true, class: "form-control select2", step: :any} %>
      </div>
  </div>
  <div class="ln_solid"></div>
  <div class="form-group">
    <%= f.label :other_criterion_id, "Nama Alternatif 2 :", class: "control-label col-md-3 col-sm-3 col-xs-12" %>
      <div class="col-md-6 col-sm-6 col-xs-12">
          <%= collection_select('', '', Alternative.where(id: @nowAlt[1]), :id, :name, {}, {:class => "form-control", disabled: true}) %>
      </div>
  </div>
  <div class="ln_solid"></div>
  <%= hidden_field(:alternative_criterion_comparison, :criterion_id, :value => @criterion.id) %>
  <%= hidden_field(:alternative_criterion_comparison, :alternative_id, :value => @nowAlt[0]) %>
  <%= hidden_field(:alternative_criterion_comparison, :other_alternative_id, :value => @nowAlt[1]) %>
  <div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= f.submit "Selanjutnya", class: "btn btn-primary pull-right" %>
      <%= link_to 'Kembali', @url, class: 'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/alternative_criterion_comparisons/edit.html.erb
<% @nowAlt = @curretAlt %>
<%= render 'form' %>
<% @url = alternative_criterion_comparisons_url %>
<% @aksi = @alternative.name %>
<% @objek = "Rubah Perbandingan" %>

app/views/alternative_criterion_comparisons/index.html.erb
<% @url = criterion_alternative_criterion_comparisons_url %>
<% @aksi = "Normalisasi" %>
<% @objek = @criterion.name %>
<%= link_to 'Ke Kriteria', criterions_path, class: 'btn btn-primary pull-left' %>
<%= link_to 'Lengkapi Perbandingan', new_criterion_alternative_criterion_comparison_path, class: 'btn btn-primary pull-right' %>
<hr>
<% unless @data.empty? %>
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>#</th>
                <% @alternatif.each do |k|%>
                <th><%= k.name %></th>
                <% end %>
              </tr>
            </thead>
            <tbody>
              <% @j = @alternatif.first %>
                <% @data.each do |d| %>
                <tr>
                  <th><%= @j.name %></th>
                  <% d.each do |dd| %>
                    <td><%= dd.round(3) %></td>
                    <% end %>
                </tr>
                <% @j = @j.next %>
                <% end %>
            </tbody>
            <tfoot>
              <tr>
                <th><i><font color="red">Jumlah</font></i></th>
                <% @sumFix.each do |s| %>
                <th><i><font color="red"><%= s.round(3) %></font></i></th>
                <% end %>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
<hr>
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>#</th>
                <% @alternatif.each do |k|%>
                <th><%= k.name %></th>
                <% end %>
                <th>Rata-rata</th>
              </tr>
            </thead>
            <tbody>
              <% @j = @alternatif.first %>
                <% @normalFix.each_with_index do |nf, inde| %>
                <tr>
                  <th><%= @j.name %></th>
                  <% nf.each do |n| %>
                    <td><%= n.round(3) %></td>
                    <% end %>
                    <th><%= @average[inde].round(3) %></th>
                </tr>
                <% @j = @j.next %>
                <% end %>
            </tbody>
            <tfoot>
              <tr>
                <th><i><font color="red">Jumlah</font></i></th>
                <% @sumNormalFix.each do |s| %>
                <th><i><font color="red"><%= s.round(3) %></font></i></th>
                <% end %>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/alternative_criterion_comparisons/new.html.erb
<% @url = criterion_alternative_criterion_comparisons_url %>
<% @aksi = @criterion.name %>
<% @objek = "Perbandingan Kriteria" %>
<% if flash[:notice] %>
<div class="callout callout-info">
  <p><%= flash[:notice] %></p>
</div>
<% end %>

<% if flash[:warning] %>
<div class="callout callout-danger">
  <p><%= flash[:warning] %></p>
</div>
<% end %>

<% unless @acc == nil %>
    <% @nowAlt = @curretAlt %>
    <% if @nowAlt[1] == nil %>
      <div class="callout callout-info">
        <h4>Selamat!</h4>

        <p>Perbandingan Alternatif untuk <%= @criterion.name %> sudah lengkap!</p>
      </div>
      <%= link_to 'Kembali', criterion_alternative_criterion_comparisons_path, class: 'btn btn-info' %>
    <% else %>
    <%= render 'form' %>
    <% end %>

    <hr>
    <%= link_to 'Ke Kriteria', criterions_path, class: 'btn btn-primary pull-left' %>
    <hr>
    <br>
    <% unless @ccs.first == nil %>
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Alternatif 1 1</th>
                    <th>Banding</th>
                    <th>Alternatif 2</th>
                    <th>Aksi</th>
                  </tr>
                </thead>
                <tbody>
                  <% nomor = 1 %>
                  <% @ccs.each do |c| %>
                  <tr>
                    <td><%= nomor %></td>
                    <td><%= c.alternative.name %></td>
                    <td><%= c.comparison %></td>
                    <td><%= c.other_alternative.name %></td>
                    <td><%= link_to 'Ubah', edit_criterion_alternative_criterion_comparison_path(c.criterion, c), class: 'btn btn-warning' %>
                        &emsp;
                       <%= link_to 'Hapus', [c.criterion, c], method: :delete, class: 'btn btn-danger', data: { confirm: 'Yakin ingin menghapus?' } %></td>
                  </tr>
                  <% nomor+=1 %>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <% else %>
    <div class="callout callout-danger">
      <h4>Error!</h4>

      <p>Alternatif belum mencukupi untuk perbandingan!</p>
    </div>
    <% end %>