config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :alternatives
  resources :criterions do
    resources :alternative_criterion_comparisons
  end
  resources :criterion_comparisons
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/criterion_comparison.rb
class CriterionComparison < ApplicationRecord
  belongs_to :criterion, class_name: 'Criterion'
  belongs_to :other_criterion, class_name: 'Criterion'
end

app/controllers/criterion_comparisons_controller.rb
class CriterionComparisonsController < ApplicationController
  require 'matrix'
  before_action :authenticate_user! , except: [:index]
  before_action :set_cc, only: [:edit, :update, :destroy]
  def index
    begin
        @data = get_comparison_table
        @c = 0
        @sumFix = []
        @data.each_with_index do |fd1, index1|
          @sumOne = 0
          @data.each_with_index do |fd, index|
            @sumOne += @data[index][index1]
          end
          @sumFix[@c] = @sumOne
          @c += 1
        end

        @s = 0
        @normalFix = []
        @average = []
        @data.each_with_index do |fd1, index1|
          @sumAv = 0
          @norm = []
          @l = 0
          @data.each_with_index do |fd, index|
            @norm[@l] = @data[index1][index] / @sumFix[index]
            @sumAv += @norm[@l]
            @l += 1
          end
          @average[@s] = @sumAv/@data.count
          @normalFix[@s] = @norm
          @s += 1
        end
        @x = 0
        @sumNormalFix = []
        @normalFix.each_with_index do |fd1, index1|
          @sumOne = 0
          @normalFix.each_with_index do |fd, index|
            @sumOne += @normalFix[index][index1]
          end
          @sumNormalFix[@x] = @sumOne
          @x += 1
        end
        @sumNormalFix[@x] = @average.inject(0, :+)
      rescue
        redirect_to new_criterion_comparison_path
        flash[:warning] = 'Lengkapi Perbandingan terlebih dahulu'
      end
  end

  def new
    @cc = CriterionComparison.new
    begin
      @curretCri = get_comparison_criterion
    rescue
      flash[:warning] = 'Kriteria tidak mencukupi untuk melakukan perbandingan'
    end
  end

  def edit
    @curretCri = [@cc.criterion_id, @cc.other_criterion_id]
  end

  def update
    if @cc.update(cc_params)
      redirect_to new_criterion_comparison_path, notice: 'Berhasil update perbandingan'
    else
      redirect_to new_criterion_comparison_path
      flash[:warning] = 'Gagal update, periksa kembali data'
    end
  end

  def create
    @cc = CriterionComparison.new(cc_params)
    if @cc.save
      redirect_to new_criterion_comparison_path, notice: 'Berhasil menambahkan perbandingan'
    else
      redirect_to new_criterion_comparison_path
      flash[:warning] = 'Gagal menyimpan, periksa kembali data'
    end
  end

  def destroy
    @cc.destroy
    redirect_to new_criterion_comparison_path, notice: 'Perbandingan berhasil dihapus'
  end

  def self.get_criterion_average
    @data = self.get_comparison_table
    @average = []
    @c = 0
    @sumFix = []
    @data.each_with_index do |fd1, index1|
      @sumOne = 0
      @data.each_with_index do |fd, index|
        @sumOne += @data[index][index1]
      end
      @sumFix[@c] = @sumOne
      @c += 1
    end

    @s = 0
    @normalFix = []

    @data.each_with_index do |fd1, index1|
      @sumAv = 0
      @norm = []
      @l = 0
      @data.each_with_index do |fd, index|
        @norm[@l] = @data[index1][index] / @sumFix[index]
        @sumAv += @norm[@l]
        @l += 1
      end
      @average[@s] = @sumAv/@data.count
      @normalFix[@s] = @norm
      @s += 1
    end
    return @average
  end

  def self.get_matrix_cri
    @data = self.get_comparison_table
    return Matrix.rows(@data)
  end
  private
  def cc_params
    params.require(:criterion_comparison).permit(:criterion_id, :comparison, :other_criterion_id)
  end

  def get_comparison_criterion
    @cri = Criterion.all.order(id: :asc) unless Criterion.nil?
    @ccs = CriterionComparison.all.order(criterion_id: :asc, other_criterion_id: :asc)
    @sumCri = @cri.count
    @curretCri1 = nil
    @curretCri2 = nil

    if @ccs.empty?
      @curretCri1 = @cri.first.id
      @curretCri2 = @cri.first.next.id
    else
      @ketemu = false
      @cri.each do |c|
        if @ccs.where(criterion_id: c.id).exists?
          @cri1 = @ccs.where(criterion_id: c.id)
          @cri2 = @ccs.where(other_criterion_id: c.id)

          @kriteria = c.next
          @cri1.each do |cr|
            @stop = false
            @cri1.each do |cr2|
              if cr2.other_criterion_id == @kriteria.id
                @stop = true
              end
              break if @stop == true
            end
            break if @stop == false
            @kriteria = @kriteria.next
          end


          if (@cri1.count + @cri2.count) < @sumCri-1
            @curretCri1 = c.id
            @curretCri2 = @kriteria.id
            @ketemu = true
          end

        else
          begin
            @curretCri1 = c.id
            @curretCri2 = c.next.id
            @ketemu = true
          rescue
            @ketemu = true
          end
        end
        break if @ketemu == true
      end
    end
    return [@curretCri1, @curretCri2]
  end

  def self.get_comparison_criterion
    @cri = Criterion.all.order(id: :asc) unless Criterion.nil?
    @ccs = CriterionComparison.all.order(criterion_id: :asc, other_criterion_id: :asc)
    @sumCri = @cri.count
    @curretCri1 = nil
    @curretCri2 = nil

    if @ccs.empty?
      @curretCri1 = @cri.first.id
      @curretCri2 = @cri.first.next.id
    else
      @ketemu = false
      @cri.each do |c|
        if @ccs.where(criterion_id: c.id).exists?
          @cri1 = @ccs.where(criterion_id: c.id)
          @cri2 = @ccs.where(other_criterion_id: c.id)

          @kriteria = c.next
          @cri1.each do |cr|
            @stop = false
            @cri1.each do |cr2|
              if cr2.other_criterion_id == @kriteria.id
                @stop = true
              end
              break if @stop == true
            end
            break if @stop == false
            @kriteria = @kriteria.next
          end


          if (@cri1.count + @cri2.count) < @sumCri-1
            @curretCri1 = c.id
            @curretCri2 = @kriteria.id
            @ketemu = true
          end

        else
          begin
            @curretCri1 = c.id
            @curretCri2 = c.next.id
            @ketemu = true
          rescue
            @ketemu = true
          end
        end
        break if @ketemu == true
      end
    end
    return [@curretCri1, @curretCri2]
  end

  def set_cc
    @cc = CriterionComparison.find(params[:id])
  end

  def get_comparison_table
    @kriteria = Criterion.all.order(id: :asc)
    @sum = @kriteria.count
    @data = []
    @n = 0
    @kriteria.each do |k|
      @dt = CriterionComparison.where(criterion_id: k.id).order(other_criterion_id: :asc)
      @i = 0
      @dat = []
      @dt.each do |dt|
        @dat[@i] = dt.comparison
        @i += 1
      end
      @data[@n] = @dat
      @n += 1
    end
    @fixdata = Array.new(@sum) { Array.new(@sum) }

    @kriteria.each_with_index do |k, i|
      (0..i).each do |n|
        if i == n
          @fixdata[i][n] = 1.to_f
          @k = n+1
          @data[i].each do |d|
            @fixdata[i][@k] = d
            @k += 1
          end
        elsif n < i
          @fixdata[i][n] = 1/@fixdata[n][i]
        end
      end
    end
    return @fixdata
  end

  def self.get_comparison_table
    @kriteria = Criterion.all.order(id: :asc)
    @sum = @kriteria.count
    @data = []
    @n = 0
    @kriteria.each do |k|
      @dt = CriterionComparison.where(criterion_id: k.id).order(other_criterion_id: :asc)
      @i = 0
      @dat = []
      @dt.each do |dt|
        @dat[@i] = dt.comparison
        @i += 1
      end
      @data[@n] = @dat
      @n += 1
    end
    @fixdata = Array.new(@sum) { Array.new(@sum) }

    @kriteria.each_with_index do |k, i|
      (0..i).each do |n|
        if i == n
          @fixdata[i][n] = 1.to_f
          @k = n+1
          @data[i].each do |d|
            @fixdata[i][@k] = d
            @k += 1
          end
        elsif n < i
          @fixdata[i][n] = 1/@fixdata[n][i]
        end
      end
    end
    return @fixdata
  end
end

app/helpers/criterion_comparisons_helper.rb
module CriterionComparisonsHelper
end

app/views/criterion_comparisons/_form.html.erb
<hr>
<%= form_for @cc, :html => {:class => "form-horizontal form-label-left"} do |f| %>
  <%= render "shared/errors", object: @cc %>
  <div class="form-group">
    <%= f.label '', "Nama Kriteria 1 :", class: "control-label col-md-3 col-sm-3 col-xs-12" %>
      <div class="col-md-6 col-sm-6 col-xs-12">
          <%= collection_select('', '', Criterion.where(id: @nowCri[0]), :id, :name, {}, {:class => "form-control", disabled: true}) %>
      </div>
  </div>
  <div class="ln_solid"></div>
  <div class="form-group">
    <%= f.label '', "Perbandingan :", class: "control-label col-md-3 col-sm-3 col-xs-12" %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.number_field :comparison, { autofocus: :true, class: "form-control select2", step: :any} %>
      </div>
  </div>
  <div class="ln_solid"></div>
  <div class="form-group">
    <%= f.label :other_criterion_id, "Nama Kriteria 2 :", class: "control-label col-md-3 col-sm-3 col-xs-12" %>
      <div class="col-md-6 col-sm-6 col-xs-12">
          <%= collection_select('', '', Criterion.where(id: @nowCri[1]), :id, :name, {}, {:class => "form-control", disabled: true}) %>
      </div>
  </div>
  <div class="ln_solid"></div>
  <%= hidden_field(:criterion_comparison, :criterion_id, :value => @nowCri[0]) %>
  <%= hidden_field(:criterion_comparison, :other_criterion_id, :value => @nowCri[1]) %>
  <div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= f.submit "Selanjutnya", class: "btn btn-primary pull-right" %>
      <%= link_to 'Kembali', @url, class: 'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/criterion_comparisons/edit.html.erb
<% if flash[:notice] %>
  <div class="callout callout-info">
    <p><%= flash[:notice] %></p>
  </div>
<% end %>

<% if flash[:warning] %>
  <div class="callout callout-danger">
    <p><%= flash[:warning] %></p>
  </div>
<% end %>

<% @nowCri = @curretCri %>
<%= render 'form' %>

<% @url = criterion_comparisons_url %>
<% @aksi = "Update Perbandingan" %>
<% @objek = "Kriteria" %>

app/views/criterion_comparisons/index.html.erb
<% if flash[:notice] %>
  <div class="callout callout-info">
    <p><%= flash[:notice] %></p>
  </div>
<% end %>

<% if flash[:warning] %>
  <div class="callout callout-danger">
    <p><%= flash[:warning] %></p>
  </div>
<% end %>
<% @url = criterion_comparisons_url %>
<% @aksi = "Normalisasi" %>
<% @objek = "Kriteria" %>
<%= link_to 'Lengkapi Perbandingan', new_criterion_comparison_path, class: 'btn btn-primary pull-right' %>
<hr>
<% unless @data.count < 2 %>
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>#</th>
                <% @kriteria.each do |k|%>
                <th><%= k.name %></th>
                <% end %>
              </tr>
            </thead>
            <tbody>
              <% @j = @kriteria.first %>
                <% @data.each do |d| %>
                <tr>
                  <th><%= @j.name %></th>
                  <% d.each do |dd| %>
                    <td><%= dd.round(3) %></td>
                    <% end %>
                </tr>
                <% @j = @j.next %>
                <% end %>
            </tbody>
            <tfoot>
              <tr>
                <th><i><font color="red">Jumlah</font></i></th>
                <% @sumFix.each do |s| %>
                <th><i><font color="red"><%= s.round(3) %></font></i></th>
                <% end %>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
<hr>
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>#</th>
                <% @kriteria.each do |k|%>
                <th><%= k.name %></th>
                <% end %>
                <th>Rata-rata</th>
              </tr>
            </thead>
            <tbody>
              <% @j = @kriteria.first %>
                <% @normalFix.each_with_index do |nf, inde| %>
                <tr>
                  <th><%= @j.name %></th>
                  <% nf.each do |n| %>
                    <td><%= n.round(3) %></td>
                    <% end %>
                    <th><%= @average[inde].round(3) %></th>
                </tr>
                <% @j = @j.next %>
                <% end %>
            </tbody>
            <tfoot>
              <tr>
                <th><i><font color="red">Jumlah</font></i></th>
                <% @sumNormalFix.each do |s| %>
                <th><i><font color="red"><%= s.round(3) %></font></i></th>
                <% end %>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/criterion_comparisons/new.html.erb
<% @url = criterion_comparisons_url %>
<% @aksi = "Perbandingan" %>
<% @objek = "Kriteria" %>
<% if flash[:notice] %>
<div class="callout callout-info">
  <p><%= flash[:notice] %></p>
</div>
<% end %>

<% if flash[:warning] %>
<div class="callout callout-danger">
  <p><%= flash[:warning] %></p>
</div>
<% end %>
<% unless @curretCri == nil %>
<% @nowCri = @curretCri %>
<% if @nowCri[1] == nil %>
  <div class="callout callout-info">
    <h4>Selamat!</h4>

    <p>Perbandingan Kriteria sudah lengkap!</p>
  </div>
  <%= link_to 'Kembali', criterion_comparisons_path, class: 'btn btn-info' %>
<% else %>
<%= render 'form' %>
<% end %>

<hr>
<% @url = criterion_comparisons_url %>
<% @aksi = "Perbandingan" %>
<% @objek = "Kriteria" %>
<hr>
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>#</th>
                <th>Kriteria 1</th>
                <th>Banding</th>
                <th>Kriteria 2</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody>
              <% nomor = 1 %>
              <% @ccs.each do |c| %>
              <tr>
                <td><%= nomor %></td>
                <td><%= c.criterion.name %></td>
                <td><%= c.comparison %></td>
                <td><%= c.other_criterion.name %></td>
                <td><%= link_to 'Ubah', edit_criterion_comparison_path(c), class: 'btn btn-warning' %>
                    &emsp;
                   <%= link_to 'Hapus', c, method: :delete, class: 'btn btn-danger', data: { confirm: 'Yakin ingin menghapus?' } %></td>
              </tr>
              <% nomor+=1 %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>