config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :alternatives
  resources :criterions do
    resources :alternative_criterion_comparisons
  end
  resources :criterion_comparisons
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/criterion.rb
class Criterion < ApplicationRecord
  has_many :AlternativeCriterionComparison
  def next
    self.class.where("id > ?", id).first
  end
end

app/controllers/criterions_controller.rb
class CriterionsController < ApplicationController
  before_action :authenticate_user! , except: [:index]
    before_action :set_criterion, only: [:edit, :update, :destroy]

    def index
      @criterions = Criterion.all.order(id: :asc)
      begin
        @allAlt = Alternative.count.to_f
        @jumlah = (@allAlt/2.to_f) * (@allAlt-1.to_f)
      rescue
        @allAlt = 0.to_f
        @jumlah = 0.to_f
      end
    end

    def new
      @criterion = Criterion.new
    end

    def edit
    end

    def create
      @criterion = Criterion.new(criterion_params)

        if @criterion.save
          redirect_to new_criterion_path, notice: 'Kriteria berhasil disimpan'
        else
          render :new
          flash[:warning] = 'Gagal simpan, periksa kembali'
        end
    end

    def update
        if @criterion.update(criterion_params)
          redirect_to edit_criterion_path, notice: 'Kriteria berhasil dirubah.'
        else
          render :edit
          flash[:warning] = 'Gagal update, periksa kembali'
        end
    end

    def destroy
      AlternativeCriterionComparison.where(criterion_id: @criterion.id).destroy_all
      CriterionComparison.where(criterion_id: @criterion.id).destroy_all
      CriterionComparison.where(other_criterion_id: @criterion.id).destroy_all
      @criterion.destroy
      redirect_to criterions_url, notice: 'Kriteria berhasil dihapus'
    end

    private
      def set_criterion
        @criterion = Criterion.find(params[:id])
      end

      def criterion_params
        params.require(:criterion).permit(:name)
      end
  end

app/helpers/criterions_helper.rb
module CriterionsHelper
end

app/views/criterions/_form.html.erb
<hr>
<%= form_for @criterion, :html => {:class => "form-horizontal form-label-left"} do |f| %>
  <%= render "shared/errors", object: @criterion %>
  <div class="form-group">
    <%= f.label :name, "Nama Kriteria :", class: "control-label col-md-3 col-sm-3 col-xs-12" %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :name, { autofocus: :true, class: "form-control select2"} %>
      </div>
  </div>
  <div class="ln_solid"></div>

  <div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= link_to 'Kembali', @url, class: 'btn btn-danger' %>
      <%= f.submit "Simpan", class: "btn btn-primary pull-right" %>
    </div>
  </div>
<% end %>

app/views/criterions/edit.html.erb
<% if flash[:notice] %>
  <div class="callout callout-info">
    <p><%= flash[:notice] %></p>
  </div>
<% end %>

<% if flash[:warning] %>
  <div class="callout callout-danger">
    <p><%= flash[:warning] %></p>
  </div>
<% end %>

<% @url = criterions_url %>
<% @aksi = "Ubah" %>
<% @objek = "Kriteria" %>
<%= notice %>
<%= render 'form' %>

app/views/criterions/index.html.erb
<% @url = alternatives_url %>
<% @aksi = "List" %>
<% @objek = "Kriteria" %>

<% if flash[:notice] %>
  <div class="callout callout-info">
    <p><%= flash[:notice] %></p>
  </div>
<% end %>

<% if flash[:warning] %>
  <div class="callout callout-danger">
    <p><%= flash[:warning] %></p>
  </div>
<% end %>

<%= link_to 'Tambah Kriteria', new_criterion_path, class: 'btn btn-primary pull-right' %>
<hr>
<% unless @criterions.first == nil %>
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <thead>
            <tr>
              <td>#</td>
              <td>Nama Kriteria</td>
              <td>Status</td>
              <td>Aksi</td>
            </tr>
          </thead>
          <tbody>
            <% nomor = 1 %>
            <% @criterions.each do |c| %>
            <tr>
              <td><%= nomor %></td>
              <td><%= c.name %></td>
              <td><%= link_to 'Perbandingan', criterion_alternative_criterion_comparisons_path(c), class: 'btn btn-primary' %>
                &emsp;
                <span class="badge bg-yellow"><%= ((AlternativeCriterionComparison.where(criterion_id: c.id).count.to_f / @jumlah ) * 100.to_f).round(2) unless @allAlt == 0 %> %</span>
              </td>
              <td>
                <%= link_to 'Ubah', edit_criterion_path(c), class: 'btn btn-warning' %>
                &emsp;
                <%= link_to 'Hapus', c, method: :delete, class: 'btn btn-danger', data: { confirm: 'Menghapus kriteria akan menghapus semua perbandingan yang terkait !' } %>
                </td>
            </tr>
            <% nomor+=1 %>
            <% end %>
          </tbody>
        </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/criterions/new.html.erb
<% @url = criterions_url %>
<% @aksi = "Tambah" %>
<% @objek = "Kriteria" %>
<% if flash[:notice] %>
<div class="callout callout-info">
  <p><%= flash[:notice] %></p>
</div>
<% end %>

<% if flash[:warning] %>
<div class="callout callout-danger">
  <p><%= flash[:warning] %></p>
</div>
<% end %>
<%= render 'form' %>