config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :alternatives
  resources :criterions do
    resources :alternative_criterion_comparisons
  end
  resources :criterion_comparisons
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <div class="container">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1.0.0
    </div>
    <strong>&copy; <%= Time.current.year %> Developed by Kelompok Tugas AHP STPK</strong>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
  <nav class="navbar navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <%= link_to '<b>STPK</b>AHP'.html_safe, root_path, class: 'navbar-brand' %>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
          <i class="fa fa-bars"></i>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
        <ul class="nav navbar-nav">
          <li class = "<%= 'active' if controller?('welcome')%>"><%= link_to 'Home', root_path %></li>
          <li class = "<%= 'active' if controller?('alternatives')%>"><%= link_to 'Alternatif', alternatives_path %></li>
          <li class = "<%= 'active' if controller?('criterions', 'alternative_criterion_comparisons')%>"> <%= link_to 'Kriteria', criterions_path %></li>
          <li class = "<%= 'active' if controller?('criterion_comparisons')%>"><%= link_to 'Banding Kriteria', criterion_comparisons_path %></li>
        </ul>
      </div>
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <% if user_signed_in? %>
            <%= link_to current_user.email %>
            <% else %>
            <a href="#">Visitor</a>
            <% end %>
          </li>
          <li class="dropdown user user-menu">
            <% if user_signed_in? %>
            <%=  link_to '', destroy_user_session_path, method: :delete, class: "fa fa-sign-out" %>
            <% else %>
            <%=  link_to '', new_user_session_path, class: "fa fa-sign-in" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>STPK AHP</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'Chart.bundle' %>
  <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body class="hold-transition skin-purple layout-top-nav">
<div class="wrapper">
<%= render 'layouts/header' %>
  <div class="content-wrapper">
    <div class="container">
      <section class="content-header">
        <h1>
          <%= @aksi %>
          <small><%= @objek %></small>
        </h1>
        <ol class="breadcrumb">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to @objek, @url %></li>
          <li class="active"><%= @aksi %></li>
        </ol>
      </section>
      <section class="content">
        <%= yield %>
      </section>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</div>

  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/layouts/devise.html.erb
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= javascript_include_tag 'application' %>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>
<body class="hold-transition login-page">
<%= yield %>
</body>